### ISSUE TITLE
Cannot compile this package

### ISSUE THREAD

**Issue by ayuguchi** [interaction-lab/openface_ros#3]
Thank you for sharing your work. I tried to use this package, but I cannot compile it.
I show you compilation errors. Do you know how to solve this problem?
```
Errors     << openface_ros:check /home/ayuguchi/catkin_ws/logs/openface_ros/build.check.002.log
CMake Error at /home/ayuguchi/catkin_ws/src/openface_ros/CMakeLists.txt:26 (message):
  message called with incorrect number of arguments

CMake Error at /home/ayuguchi/catkin_ws/src/openface_ros/CMakeLists.txt:27 (get_filename_component):
  get_filename_component called with incorrect number of arguments

CMake Error at /home/ayuguchi/catkin_ws/src/openface_ros/CMakeLists.txt:28 (message):
  message called with incorrect number of arguments

/usr/bin/cc
cd /home/ayuguchi/catkin_ws/build/openface_ros; catkin build --get-env openface_ros | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
```
FYI, my pc's environments are Ubuntu 14.04,  ROS indigo, OpenCV 3.2, and Dlib 19.4.

**Comment by bmcdorman** [comment]
The version of CMake bundled with ROS Indigo / Ubuntu 14.04 might be too old to compile the package. One of us tried to compile on Indigo/14.04 a while back and it was a very difficult experience. It should work well with ROS Jade and Kinetic on 15.04 and 16.04, respectively.

Hope this helps!

**Comment by ayuguchi** [comment]
@bmcdorman Thank you very much for your reply & advice. So I can compile this package on ROS Kinetic and Indigo because I clone OpenFace from your lab's fork repo. When I met that problem, I cloned from https://github.com/TadasBaltrusaitis/OpenFace.
I misread this repo's README. I'm very sorry for taking your time.
